apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-iam
  labels:
    provider: gcp
    engine.io/composition: iam
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: gcp-service-account
    base:
      apiVersion: iam.gcp.upbound.io/v1beta1
      kind: ServiceAccount
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
