version: 2
before:
  hooks:
    - go mod tidy

gomod:
  proxy: false

builds:
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath", "-gcflags=all=-l"]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -buildid=
    hooks:
      post:
        - cmd: upx --best --lzma {{ .Path }}
          env:
            - UPX_AVAILABLE=true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-SHA256SUMS"
  algorithm: sha256

sboms:
  - id: archives
    artifacts: archive
    documents:
      - "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}.sbom"

signs:
  - artifacts: archive
    args: ["sign", "--output", "${signature}", "${artifact}"]
    signature: "${artifact}.sig"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  footer: |

    ---

    _Released with [GoReleaser](https://goreleaser.com)!_
