apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: digitalocean-loadbalancer
  labels:
    provider: digitalocean
    engine.io/composition: loadbalancer
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: digitalocean-loadbalancer
    base:
      apiVersion: digitalocean.upbound.io/v1beta1
      kind: LoadBalancer
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.region"
