apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
  labels:
    app: engine
    component: configuration
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://kubernetes.default.svc
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      name: in-cluster
    contexts:
    - context:
        cluster: in-cluster
        user: serviceaccount
      name: default-context
    current-context: default-context
    users:
    - name: serviceaccount
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
