apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engine-ui
  labels:
    app: engine-ui
    component: ui-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: engine-ui.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: engine-ui
            port:
              number: 8080
