apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: hetzner-network
  labels:
    provider: hetzner
    engine.io/composition: networking
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: hetzner-network
    base:
      apiVersion: hetzner.upbound.io/v1alpha1
      kind: Network
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
  - name: hetzner-firewall
    base:
      apiVersion: hetzner.upbound.io/v1alpha1
      kind: Firewall
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
