apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: hetzner-storage
  labels:
    provider: hetzner
    engine.io/composition: storage
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: hetzner-volume
    base:
      apiVersion: hetzner.upbound.io/v1alpha1
      kind: Volume
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.tier"
      toFieldPath: "spec.forProvider.size"
      transforms:
      - type: map
        map:
          micro: "20"
          small: "50"
          pro: "100"
