apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-database
  labels:
    provider: azure
    engine.io/composition: database
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: azure-sql-server
    base:
      apiVersion: sql.azure.upbound.io/v1beta1
      kind: Server
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.version"
      transforms:
      - type: map
        map:
          default: "12.0"
