apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-iam
  labels:
    provider: azure
    engine.io/composition: iam
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: azure-role-assignment
    base:
      apiVersion: authorization.azure.upbound.io/v1beta1
      kind: RoleAssignment
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
