apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-vnet
  labels:
    provider: azure
    engine.io/composition: networking
spec:
  compositeTypeRef:
    apiVersion: engine.io/v1alpha1
    kind: XCompute
  resources:
  - name: azure-vnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.addressSpace"
      transforms:
      - type: map
        map:
          default: "10.0.0.0/16"
  - name: azure-subnet-public
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.addressPrefix"
      transforms:
      - type: map
        map:
          default: "10.0.1.0/24"
  - name: azure-subnet-private
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.addressPrefix"
      transforms:
      - type: map
        map:
          default: "10.0.2.0/24"
  - name: azure-nsg
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: SecurityGroup
    patches:
    - fromFieldPath: "spec.provider"
      toFieldPath: "metadata.labels[engine.io/provider]"
    - fromFieldPath: "spec.region"
      toFieldPath: "spec.forProvider.location"
